---
- name: Deploying nginx webserver
  hosts: web
  tasks:
    - name: Install nginx latest version and start service
      apt:
        name: nginx
        state: latest
    - name: Start nginx service
      ansible.builtin.service:
        name: nginx
        state: started
    - name: Allow Uncomplicated Firewall for nginx
      ufw:
        rule: allow
        port: 80
        proto: tcp
    - name: Copy newindex.html to public index.html
      ansible.builtin.copy:
        src: ./index.html
        dest: /var/www/html/index.nginx-debian.html
        follow: yes
    - name: Reload nginx webserver
      ansible.builtin.service:
        name: nginx
        state: reloaded

- name: Ensure SQLite3 is installed
  hosts: db
  tasks: 
    - name: Ensure SQLite3 is installed
      ansible.builtin.package:
        name: sqlite3
        state: present
    - name: Ensure SQLite-Utils is installed
      ansible.builtin.package:
        name: sqlite-utils
        state: present
    - name: Create SQLite3 database file
      ansible.builtin.command:
        cmd: sqlite3 /root/sqll3.db "VACUUM;"
      args:
        creates: /root/sqll3.db
    - name: Create a table with a primary key and default values
      ttafsir.sqlite_utils.create:
        if_not_exists: true
        db_path: /root/sqll3.db
        table: cats
        columns:
          id: int
          name: str
          breed: str
          weight: float
        pk: id
        defaults:
          breed: "Unknown"
